version: "3.9"

services:
  backend:
    build: ../TunahanYilmaz-case-backend
    container_name: PassportX-backend
    environment:
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - APP_PORT=8000
      - APP_ENV=production
      - DB_PATH=/data/dpp.db
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@passportx.com}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - db_data:/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: .
    container_name: PassportX-frontend
    enviroment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
